Add app config tab
emberjs/ember-inspector pull request #1577
Opened 2021-05-12 15:30 UTC by hannakim91

## Description
Added app config tab to info tab. Currently longer objects get cut off. Will look at changing that in the future. 

## Screenshots

<img width="1141" alt="Screen Shot 2021-05-12 at 9 30 02 AM" src="https://user-images.githubusercontent.com/62962173/118002194-a25a4c80-b304-11eb-865b-e0025be8e402.png">

2021-05-12 20:03 UTC, rwwagner90 requested changes

2021-05-12 20:03 UTC, rwwagner90 commented on app/routes/app-config.js
> +    console.log('port', port);
```suggestion
```

2021-05-12 20:03 UTC, rwwagner90 commented on app/routes/app-config.js
> +        console.log('message', message.emberCliConfig);
```suggestion
```

2021-05-12 20:03 UTC, rwwagner90 commented on app/routes/libraries.js
> +        console.log('libraries', message.libraries)
```suggestion
```

2021-05-12 20:03 UTC, rwwagner90 commented on ember_debug/general-debug.js
> +        console.log(config);
```suggestion
```

2021-05-12 20:03 UTC, rwwagner90 commented on tests/unit/controllers/app-config-test.js
> +  test('it exists', function(assert) {
We should probably delete this empty test file.

2021-05-12 20:03 UTC, rwwagner90 commented on tests/unit/routes/app-config-test.js
> +  setupTest(hooks);
We should probably delete this empty test file.

2021-05-12 21:15 UTC, nummi commented
Looks great to me! :+1:

2021-05-13 02:01 UTC, rwwagner90 commented on app/routes/app-config.js
> +  version: readOnly('config.VERSION'),
```suggestion
```

2021-05-13 02:02 UTC, rwwagner90 approved these changes

2021-05-13 02:19 UTC, rwwagner90 commented on app/routes/app-config.js
> +import { readOnly } from '@ember/object/computed';
```suggestion
```

2021-05-13 02:20 UTC, rwwagner90 commented on app/routes/app-config.js
> +
```suggestion
```

2021-05-13 02:29 UTC, merged